version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'videosapp'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mariadb:10.5.9
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: 'videosapp'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql